# ----
# Site

title: BinaryExile
url: "https://binaryexile.github.io/"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: BinaryExile Cheat Sheets.
author:
  name: BinaryExile
  email:
  twitter: # twitter username without the @ symbol
social:
  name: BinaryExile
  links:
    -
# -----
# Build

permalink: pretty

highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
